custom_metrics:
- earne_mae_load
- earne_mae_pv
dataset:
  dir: datasets/earne
  format: earne_loader_new
  name: earne_exp2
  task: graph
  task_type: regression
  transductive: false
earne_data:
  cadence_minutes: 15
  days: 365
  dual_read: false
  graph_mode: learned_corr
  mapping_csv: ../../exploratory-data-analysis/output/weather_hive/zip_to_station_mapping.csv
  metadata_csv: ../../exploratory-data-analysis/output/mac_overview_updated.csv
  n_user: 50
  norm_mode: zero_log
  processed_root: datasets/earne
  raw_data_path: ../../exploratory-data-analysis/output/clean_data_hive
  weather_features:
  - solar_radiation_avg
  - solar_radiation_max
  - sunshine_duration_min
  - air_temperature
  - soil_temp_5cm
  weather_hive: ../../exploratory-data-analysis/output/weather_hive
  zipcode_coords: ../../exploratory-data-analysis/assets/zipcode_coordinate.csv
gnn:
  act: relu
  att_heads: 4
  batchnorm: false
  dim_inner: 64
  dropout: 0.1
  layer_type: gatconv
  layers_mp: 2
  layers_post_mp: 1
  layers_pre_mp: 0
  stage_type: stack
model:
  dim_in: 1
  graph_pooling: add
  loss_fun: earne_loss
  type: earne_network
num_workers: 4
optim:
  base_lr: 0.001
  max_epoch: 1
  optimizer: adam
  scheduler: cos
out_dir: results/earne_exp2_grid_exp2_func_check
train:
  batch_size: 32
  ckpt_period: 10
  eval_period: 1
  mode: example
  physics_weight: 0.0
