[project]
name = "graphgym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "duckdb>=1.5.1",
  "ipython",
  "joblib>=1.5.3",
  "lightning>=2.6.5",
  "matplotlib>=3.10.8",
  "numpy>=1.26.4",
  "ogb>=1.3.6",
  "pandas>=2.3.3",
  "polars",
  "pyarrow",
  "scikit-learn>=1.7.2",
  "scipy",
  "tensorboardX",
  "torch>=2.10.0",
  "torch-geometric",
  "wandb>=0.26.0",
  "yacs>=0.1.8",
]

[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.uv.workspace]
members = ["torch-geometric", "graphgym"]
